package com.pojo;

// Generated Mar 12, 2019 11:57:25 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Addevent generated by hbm2java
 */
public class Addevent implements java.io.Serializable {

	private Integer eid;
	private Registration registration;
	private String eventtype;
	private String eventname;
	private Double cost;
	private String facility;
	private String eventimage;
	private Set bookings = new HashSet(0);
	private Set feedbacks = new HashSet(0);

	public Addevent() {
	}

	public Addevent(Registration registration, String eventtype, String eventname, Double cost, String facility,
			String eventimage, Set bookings, Set feedbacks) {
		this.registration = registration;
		this.eventtype = eventtype;
		this.eventname = eventname;
		this.cost = cost;
		this.facility = facility;
		this.eventimage = eventimage;
		this.bookings = bookings;
		this.feedbacks = feedbacks;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public String getEventtype() {
		return this.eventtype;
	}

	public void setEventtype(String eventtype) {
		this.eventtype = eventtype;
	}

	public String getEventname() {
		return this.eventname;
	}

	public void setEventname(String eventname) {
		this.eventname = eventname;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public String getFacility() {
		return this.facility;
	}

	public void setFacility(String facility) {
		this.facility = facility;
	}

	public String getEventimage() {
		return this.eventimage;
	}

	public void setEventimage(String eventimage) {
		this.eventimage = eventimage;
	}

	public Set getBookings() {
		return this.bookings;
	}

	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}

	public Set getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set feedbacks) {
		this.feedbacks = feedbacks;
	}

}
