package com.pojo;

// Generated Mar 12, 2019 11:57:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * Colntactus generated by hbm2java
 */
public class Colntactus implements java.io.Serializable {

	private Integer cid;
	private String cname;
	private String email;
	private String message;
	private String phno;

	public Colntactus() {
	}

	public Colntactus(String cname, String email, String message, String phno) {
		this.cname = cname;
		this.email = email;
		this.message = message;
		this.phno = phno;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getPhno() {
		return this.phno;
	}

	public void setPhno(String phno) {
		this.phno = phno;
	}

}
