package com.pojo;

// Generated Mar 12, 2019 11:57:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * Feedback generated by hbm2java
 */
public class Feedback implements java.io.Serializable {

	private Integer fid;
	private Addevent addevent;
	private Registration registration;
	private String message;

	public Feedback() {
	}

	public Feedback(Addevent addevent, Registration registration, String message) {
		this.addevent = addevent;
		this.registration = registration;
		this.message = message;
	}

	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

	public Addevent getAddevent() {
		return this.addevent;
	}

	public void setAddevent(Addevent addevent) {
		this.addevent = addevent;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
