package com.pojo;

// Generated Mar 12, 2019 11:57:25 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Registration implements java.io.Serializable {

	private Integer rid;
	private Role role;
	private String fname;
	private String lname;
	private String email;
	private String password;
	private Date regdate;
	private Set bookings = new HashSet(0);
	private Set feedbacks = new HashSet(0);
	private Set addevents = new HashSet(0);

	public Registration() {
	}

	public Registration(Role role, String fname, String lname, String email, String password, Date regdate,
			Set bookings, Set feedbacks, Set addevents) {
		this.role = role;
		this.fname = fname;
		this.lname = lname;
		this.email = email;
		this.password = password;
		this.regdate = regdate;
		this.bookings = bookings;
		this.feedbacks = feedbacks;
		this.addevents = addevents;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegdate() {
		return this.regdate;
	}

	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	public Set getBookings() {
		return this.bookings;
	}

	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}

	public Set getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set feedbacks) {
		this.feedbacks = feedbacks;
	}

	public Set getAddevents() {
		return this.addevents;
	}

	public void setAddevents(Set addevents) {
		this.addevents = addevents;
	}

}
